sudo: required

services:
  - docker

install:
  - docker build -t dockertestimage .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run --privileged -e ci_env -ti dockertestimage /bin/bash -c
     "python3 -m pytest --cov=oommfc --cov-config .coveragerc &&
      bash <(curl -s https://codecov.io/bash) -t a253c171-1619-4812-944c-89918bf5c98d"

notifications:
  slack: joommf:eqKxGPXuUP3LxnOfxg7GWgDF