sudo: required

services:
  - docker

install:
  - docker build -t dockertestimage .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run --privileged -e ci_env -ti --name testcontainer dockertestimage -c "make travistest"

notifications:
  slack: joommf:eqKxGPXuUP3LxnOfxg7GWgDF