language: python

python:
  - "3.5"

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

install: pip install codecov pytest-cov matplotlib pandas ipywidgets git+https://github.com/joommf/oommfodt.git git+https://github.com/joommf/discretisedfield.git git+https://github.com/joommf/micromagneticmodel.git

script: py.test --cov=oommfc --cov-config .coveragerc

after_success:
  codecov

notifications:
  slack: joommf:eqKxGPXuUP3LxnOfxg7GWgDF
