# name of the conda environment
name: oommfc_docs

# add channel for pandoc
channels:
  - asmeurer

dependencies:
  - pandoc
  - nbformat
  - pip:
      - nbsphinx
      - matplotlib
      - pandas
      - git+https://github.com/joommf/oommffield.git
      - git+https://github.com/joommf/oommfodt.git